
all: dev

clean:
	yarn run clean

install:
	yarn

build:
	yarn run build

start:
	yarn run start

start-dev:
	yarn run start-dev

serve:
	yarn run serve

test:
	yarn run test

test-unit:
	yarn run test-unit

test-int:
	yarn run test-int

test-ci:
	yarn run test-ci

validate:
	yarn run eslint

.PHONY: clean install build start dev serve test test-ci
